In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import r2_score, mean_squared_error, root_mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from datetime import datetime, timedelta

In [2]:
light_on_Merged_FullDataSet = pd.read_csv('../data/MergedData.csv')
light_on = light_on_Merged_FullDataSet #.head(9000)

/var/folders/nl/hqcw9pqd0ns4q0b61syv0q2m0000gn/T/ipykernel_15594/2186112238.py:1: DtypeWarning: Columns (16,22,23,26,27,29,30,31,32,33,34,35,36,38,42,43,44,45) have mixed types. Specify dtype option on import or set low_memory=False.
  light_on_Merged_FullDataSet = pd.read_csv('../data/MergedData.csv')

convert columns to appropriate format

In [3]:
cols = ['spn', 'fmi', 'AcceleratorPedal', 'BarometricPressure', 'CruiseControlSetSpeed', 'DistanceLtd', 'EngineCoolantTemperature', 'EngineLoad', 'EngineOilPressure', 'EngineOilTemperature', 'EngineRpm', 'EngineTimeLtd', 'FuelLevel', 'FuelLtd', 'FuelRate', 'FuelTemperature', 'IntakeManifoldTemperature', 'LampStatus', 'Speed', 'Throttle', 'TurboBoostPressure']
light_on[cols] = light_on[cols].apply(pd.to_numeric, errors='coerce', axis=1)
light_on

,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,...,FuelTemperature,IgnStatus,IntakeManifoldTemperature,LampStatus,ParkingBrake,ServiceDistance,Speed,SwitchedBatteryVoltage,Throttle,TurboBoostPressure
0,0,1,990349,2015-02-21 10:47:13.000,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,NaN,False,78.8,1023.0,True,NaN,0.00000,3276.75,NaN,0.00
1,1,2,990360,2015-02-21 11:34:34.000,NaN,NaN,unknown,unknown,unknown,unknown,...,NaN,True,NaN,1279.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,3,990364,2015-02-21 11:35:31.000,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,NaN,1279.0,NaN,NaN,NaN,NaN,NaN,NaN
3,3,4,990370,2015-02-21 11:35:33.000,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,unknown,...,NaN,True,NaN,1279.0,NaN,NaN,NaN,NaN,NaN,NaN
4,4,5,990416,2015-02-21 11:39:41.000,NaN,NaN,22281684P01*22357957P01*22362082P01*,13063430,0USA13_13_0415_2238A,VOLVO,...,NaN,NaN,NaN,16639.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1061319,1187330,1248454,123904424,2020-03-06 14:00:26.000,Low (Severity Low) Catalyst Tank Level,NaN,04384413*22383729*082218154102*60701732*G1*BGT*,80156139,6X1u17D1500000000,CMMNS,...,NaN,NaN,NaN,1023.0,NaN,NaN,NaN,NaN,NaN,NaN
1061320,1187331,1248455,123905139,2020-03-06 14:04:23.000,Condition Exists Engine Protection Torque Derate,NaN,04358814*06099720*030816202706*09400153*G1*BDR*,79932020,6X1u13D1500000000,CMMNS,...,32.0,True,98.6,18431.0,False,NaN,65.01096,NaN,73.2,7.83
1061321,1187332,1248456,123905996,2020-03-06 14:13:38.000,Abnormal Rate of Change Aftertreatment 1 Intak...,NaN,05317106*05100987*050719120655*09401585*G1*BDR*,79880653,6X1u13D1500000000,CMMNS,...,NaN,True,91.4,17407.0,NaN,NaN,66.57410,NaN,100.0,6.96
1061322,1187333,1248457,123906113,2020-03-06 14:14:13.000,Low (Severity Medium) Engine Coolant Level,NaN,04384413*22544852*090619141107*60701756*G1*BGT*,NaN,NaN,NaN,...,NaN,True,100.4,1023.0,False,NaN,11.84489,14.1,100.0,1.74
1061323,1187334,1248458,123906131,2020-03-06 14:15:34.000,Low (Severity Medium) Engine Coolant Level,NaN,04384413*22544852*090619141107*60701756*G1*BGT*,NaN,NaN,NaN,...,NaN,NaN,NaN,1023.0,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
light_on['spn_fmi'] = light_on['spn'].astype(str) + '_' + light_on['fmi'].astype(str)
light_on

,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,...,IgnStatus,IntakeManifoldTemperature,LampStatus,ParkingBrake,ServiceDistance,Speed,SwitchedBatteryVoltage,Throttle,TurboBoostPressure,spn_fmi
0,0,1,990349,2015-02-21 10:47:13.000,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,78.8,1023.0,True,NaN,0.00000,3276.75,NaN,0.00,111.0_17.0
1,1,2,990360,2015-02-21 11:34:34.000,NaN,NaN,unknown,unknown,unknown,unknown,...,True,NaN,1279.0,NaN,NaN,NaN,NaN,NaN,NaN,629.0_12.0
2,2,3,990364,2015-02-21 11:35:31.000,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,1279.0,NaN,NaN,NaN,NaN,NaN,NaN,1807.0_2.0
3,3,4,990370,2015-02-21 11:35:33.000,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,unknown,...,True,NaN,1279.0,NaN,NaN,NaN,NaN,NaN,NaN,1807.0_2.0
4,4,5,990416,2015-02-21 11:39:41.000,NaN,NaN,22281684P01*22357957P01*22362082P01*,13063430,0USA13_13_0415_2238A,VOLVO,...,NaN,NaN,16639.0,NaN,NaN,NaN,NaN,NaN,NaN,4364.0_17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1061319,1187330,1248454,123904424,2020-03-06 14:00:26.000,Low (Severity Low) Catalyst Tank Level,NaN,04384413*22383729*082218154102*60701732*G1*BGT*,80156139,6X1u17D1500000000,CMMNS,...,NaN,NaN,1023.0,NaN,NaN,NaN,NaN,NaN,NaN,1761.0_17.0
1061320,1187331,1248455,123905139,2020-03-06 14:04:23.000,Condition Exists Engine Protection Torque Derate,NaN,04358814*06099720*030816202706*09400153*G1*BDR*,79932020,6X1u13D1500000000,CMMNS,...,True,98.6,18431.0,False,NaN,65.01096,NaN,73.2,7.83,1569.0_31.0
1061321,1187332,1248456,123905996,2020-03-06 14:13:38.000,Abnormal Rate of Change Aftertreatment 1 Intak...,NaN,05317106*05100987*050719120655*09401585*G1*BDR*,79880653,6X1u13D1500000000,CMMNS,...,True,91.4,17407.0,NaN,NaN,66.57410,NaN,100.0,6.96,3216.0_10.0
1061322,1187333,1248457,123906113,2020-03-06 14:14:13.000,Low (Severity Medium) Engine Coolant Level,NaN,04384413*22544852*090619141107*60701756*G1*BGT*,NaN,NaN,NaN,...,True,100.4,1023.0,False,NaN,11.84489,14.1,100.0,1.74,111.0_18.0
1061323,1187334,1248458,123906131,2020-03-06 14:15:34.000,Low (Severity Medium) Engine Coolant Level,NaN,04384413*22544852*090619141107*60701756*G1*BGT*,NaN,NaN,NaN,...,NaN,NaN,1023.0,NaN,NaN,NaN,NaN,NaN,NaN,111.0_18.0

In [5]:
# dummy_columns = pd.get_dummies(light_on, columns = ['spn_fmi']) # temporarily commented out in order to reduce file size by removing the dummy columns 
dummy_columns = light_on

In [6]:
dummy_columns['is_fullderate'] = (dummy_columns['spn'] == 5246).astype(int)

In [7]:
dummy_columns = dummy_columns.sort_values(['EquipmentID', 'EventTimeStamp'])
dummy_columns['is_fullderate_group'] = dummy_columns.groupby('EquipmentID')['is_fullderate'].cumsum()

In [8]:
Num_of_FullDerates_inDataSet = dummy_columns['is_fullderate_group'].sum()
Num_of_FullDerates_inDataSet # 1

np.int64(393460)

In [9]:
dummy_columns['EquipID_Index'] = dummy_columns['EquipmentID'].astype(str) + '_' + dummy_columns['is_fullderate_group'].astype(str)

dummy_columns.to_csv('../data/TwentyRows_Preceding_SPN5246_LightOn_Truck_Identifier_SubsequentTrialRun.csv')

In [10]:
def check_time_intervals(df, EventTimeStamp='EventTimeStamp', condition_column='spn', condition_value=5246, interval_column_name='time_to_next_SPN5246'):
    """
    Calculate the time interval between the current row and the next row(s) that meet a specific condition.
    
    Parameters:
    -----------
    df : pandas.DataFrame
        The dataframe containing the timestamp and condition columns.
    EventTimeStamp : str
        The name of the column containing datetime values.
    condition_column : str, optional
        The name of the column to check for the condition. If None, all rows are considered.
    condition_value : any, optional
        The value to check for in the condition column. If None, all rows are considered.
    interval_column_name : str, optional
        The name for the new column that will store the time interval information.
        Default is 'time_to_next_condition'.
    
    Returns:
    --------
    pandas.DataFrame
        The original dataframe with an additional column showing the time interval
        to the next row meeting the condition.
    """
    # Ensure the timestamp column is in datetime format
    df[EventTimeStamp] = pd.to_datetime(df[EventTimeStamp])
    
    # Create a copy of the dataframe to avoid modifying the original
    result_df = df.copy()
    
    # Add a column to store the time intervals with the specified name
    result_df[interval_column_name] = timedelta(days=9999999)  # Initialize with a large timedelta
   
   
   # if result_df['spn']==5246:
        #result_df[interval_column_name] = timedelta(0)
   # else:
        
    # Filter rows that meet the condition if a condition is specified
    if condition_column is not None and condition_value is not None:
        condition_rows = df[df[condition_column] == condition_value]
    else:
        condition_rows = df
    
    # For each row in the dataframe
    for i in range(len(df) - 1):
        current_time = df.iloc[i][EventTimeStamp]
        current_EquipmentID = df.iloc[i]['EquipmentID']
        
        # Find the next row that meets the condition and is after the current row
        next_condition_rows = condition_rows[(condition_rows[EventTimeStamp] > current_time) & (condition_rows['EquipmentID'] == current_EquipmentID)]
        
        if not next_condition_rows.empty:
            # Get the earliest next condition time
            next_condition_time = next_condition_rows[EventTimeStamp].min()
            
            # Calculate the time difference
            time_diff = next_condition_time - current_time
            
            # Store the result in the specified column
            result_df.iloc[i, result_df.columns.get_loc(interval_column_name)] = time_diff
    
    return result_df

In [11]:
TimeIntervalColumn_AddedTo_DummyColumns = check_time_intervals(dummy_columns, EventTimeStamp='EventTimeStamp', condition_column='spn', condition_value=5246, interval_column_name='time_to_next_SPN5246') 
TimeIntervalColumn_AddedTo_DummyColumns

,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,...,ServiceDistance,Speed,SwitchedBatteryVoltage,Throttle,TurboBoostPressure,spn_fmi,is_fullderate,is_fullderate_group,EquipID_Index,time_to_next_SPN5246
43931,48303,49415,2363162,2015-05-11 13:11:20,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,NaN,4.475814,3276.75,14.4,0.58,639.0_2.0,0,0,301_0,428 days 05:59:47
45693,50251,51363,2400445,2015-05-13 08:22:32,Condition Exists Cruise Control Enable Switch,NaN,unknown,unknown,unknown,unknown,...,NaN,64.637170,3276.75,89.6,4.64,596.0_31.0,0,0,301_0,426 days 10:48:35
50271,55260,57330,2482983,2015-05-18 09:34:05,Abnormal Rate of Change Aftertreatment 1 Outle...,NaN,PC4__1284P4C_2*,6U13D13,MX,PCAR,...,NaN,63.525490,3276.75,0.0,20.30,3226.0_10.0,0,0,301_0,421 days 09:37:02
54326,59636,61706,2554027,2015-05-21 13:57:35,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,NaN,4.364162,3276.75,12.0,1.45,639.0_2.0,0,0,301_0,418 days 05:13:32
54418,59731,61801,2555325,2015-05-21 14:54:32,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,NaN,NaN,NaN,639.0_2.0,0,0,301_0,418 days 04:16:35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4036,4494,4495,1052146,2015-02-24 16:24:05,Low (Severity Medium) Catalyst Tank Level,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,NaN,NaN,NaN,NaN,NaN,1761.0_18.0,0,0,R1762_0,9999999 days 00:00:00
5907,6438,6439,1089561,2015-02-26 13:12:11,NaN,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,NaN,2.058292,3276.75,0.0,0.29,5848.0_9.0,0,0,R1762_0,9999999 days 00:00:00
5915,6446,6447,1090499,2015-02-26 13:50:59,NaN,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,NaN,NaN,NaN,NaN,NaN,5848.0_9.0,0,0,R1762_0,9999999 days 00:00:00
4472,4952,4953,1059704,2015-02-25 06:08:43,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,NaN,4.378725,3276.75,0.0,1.74,639.0_2.0,0,0,R1764_0,9999999 days 00:00:00
4512,4999,5000,1060204,2015-02-25 06:38:40,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,NaN,NaN,NaN,639.0_2.0,0,0,R1764_0,9999999 days 00:00:00

In [12]:
def convert_to_hours(delta):
    total_seconds = delta.dt.total_seconds()
    hours = (total_seconds / 3600).astype(float)
    return hours

In [13]:
TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246'] = convert_to_hours(TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246']) 
TimeIntervalColumn_AddedTo_DummyColumns

,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,...,ServiceDistance,Speed,SwitchedBatteryVoltage,Throttle,TurboBoostPressure,spn_fmi,is_fullderate,is_fullderate_group,EquipID_Index,time_to_next_SPN5246
43931,48303,49415,2363162,2015-05-11 13:11:20,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,NaN,4.475814,3276.75,14.4,0.58,639.0_2.0,0,0,301_0,1.027800e+04
45693,50251,51363,2400445,2015-05-13 08:22:32,Condition Exists Cruise Control Enable Switch,NaN,unknown,unknown,unknown,unknown,...,NaN,64.637170,3276.75,89.6,4.64,596.0_31.0,0,0,301_0,1.023481e+04
50271,55260,57330,2482983,2015-05-18 09:34:05,Abnormal Rate of Change Aftertreatment 1 Outle...,NaN,PC4__1284P4C_2*,6U13D13,MX,PCAR,...,NaN,63.525490,3276.75,0.0,20.30,3226.0_10.0,0,0,301_0,1.011362e+04
54326,59636,61706,2554027,2015-05-21 13:57:35,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,NaN,4.364162,3276.75,12.0,1.45,639.0_2.0,0,0,301_0,1.003723e+04
54418,59731,61801,2555325,2015-05-21 14:54:32,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,NaN,NaN,NaN,639.0_2.0,0,0,301_0,1.003628e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4036,4494,4495,1052146,2015-02-24 16:24:05,Low (Severity Medium) Catalyst Tank Level,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,NaN,NaN,NaN,NaN,NaN,1761.0_18.0,0,0,R1762_0,2.400000e+08
5907,6438,6439,1089561,2015-02-26 13:12:11,NaN,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,NaN,2.058292,3276.75,0.0,0.29,5848.0_9.0,0,0,R1762_0,2.400000e+08
5915,6446,6447,1090499,2015-02-26 13:50:59,NaN,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,NaN,NaN,NaN,NaN,NaN,5848.0_9.0,0,0,R1762_0,2.400000e+08
4472,4952,4953,1059704,2015-02-25 06:08:43,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,NaN,4.378725,3276.75,0.0,1.74,639.0_2.0,0,0,R1764_0,2.400000e+08
4512,4999,5000,1060204,2015-02-25 06:38:40,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,NaN,NaN,NaN,639.0_2.0,0,0,R1764_0,2.400000e+08

In [14]:
TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246'].min()

np.float64(0.0002777777777777778)

In [15]:
TimeIntervalColumn_AddedTo_DummyColumns[TimeIntervalColumn_AddedTo_DummyColumns['spn'] == 5246].index.tolist()

[469200,
 1047290,
 1048845,
 1048851,
 1051303,
 1056781,
 1057357,
 343927,
 343930,
 280529,
 280921,
 298985,
 298990,
 328220,
 328224,
 918761,
 924240,
 929560,
 929639,
 930852,
 930853,
 930864,
 930867,
 930874,
 930875,
 931237,
 931238,
 931885,
 931925,
 933331,
 933662,
 933669,
 933744,
 934999,
 935319,
 913693,
 75918,
 75303,
 75304,
 76153,
 76386,
 97677,
 97982,
 193307,
 193523,
 304515,
 305062,
 232952,
 234731,
 331175,
 333365,
 31360,
 31411,
 32353,
 32351,
 252416,
 252417,
 292397,
 292496,
 341876,
 342374,
 364412,
 364439,
 87194,
 87640,
 347569,
 348630,
 43367,
 43373,
 104740,
 104741,
 105041,
 105042,
 107161,
 107162,
 110605,
 110862,
 382685,
 382882,
 382923,
 383163,
 298775,
 303412,
 352591,
 353820,
 353963,
 115900,
 115941,
 208633,
 210475,
 409404,
 410105,
 55384,
 55890,
 148650,
 149250,
 150206,
 150209,
 322529,
 322537,
 324343,
 324646,
 330103,
 330219,
 128157,
 129111,
 338510,
 338507,
 338491,
 338488,
 338493,
 338503,
 338996,
 345703,
 345877,
 150370,
 150372,
 151581,
 151583,
 152581,
 152586,
 153770,
 153774,
 154627,
 154640,
 154962,
 154963,
 155321,
 155324,
 155844,
 156079,
 171277,
 171279,
 171483,
 171484,
 171822,
 172386,
 379444,
 379452,
 380429,
 380473,
 385144,
 385211,
 391548,
 391716,
 392181,
 392862,
 212821,
 213815,
 448630,
 448714,
 448776,
 448849,
 449478,
 449581,
 450285,
 450311,
 362492,
 363045,
 341229,
 342389,
 121495,
 121652,
 252276,
 252277,
 254279,
 254285,
 263801,
 263803,
 264416,
 264418,
 276277,
 276286,
 278078,
 278082,
 278745,
 279230,
 279864,
 400396,
 400398,
 400879,
 400881,
 414396,
 414397,
 352202,
 352234,
 347450,
 347501,
 368666,
 368692,
 568880,
 568910,
 568909,
 577642,
 577700,
 577699,
 578649,
 578648,
 579881,
 615491,
 615675,
 615674,
 615715,
 615714,
 615718,
 615717,
 615724,
 276577,
 302616,
 303017,
 303016,
 303019,
 303046,
 304220,
 314475,
 314530,
 314529,
 314577,
 319712,
 319881,
 321666,
 321713,
 323158,
 323174,
 323173,
 323181,
 324037,
 324053,
 330115,
 346109,
 346131,
 346130,
 346135,
 366056,
 366109,
 397033,
 397106,
 397105,
 397140,
 402570,
 402577,
 405335,
 405355,
 406003,
 406022,
 406125,
 406188,
 408024,
 408083,
 409961,
 410009,
 410053,
 410076,
 411699,
 411717,
 418821,
 418830,
 418829,
 418861,
 433007,
 433103,
 433102,
 433104,
 433228,
 433563,
 435427,
 442543,
 442567,
 557575,
 557677,
 557675,
 557713,
 565474,
 565494,
 565493,
 565557,
 566360,
 566461,
 571475,
 571558,
 571557,
 571658,
 572514,
 572604,
 577646,
 577810,
 577809,
 577828,
 577837,
 594098,
 610251,
 614615,
 635669,
 639227,
 585660,
 585697,
 585696,
 585710,
 587505,
 587562,
 638181,
 638224,
 638223,
 638277,
 638312,
 638446,
 638445,
 638456,
 638879,
 640762,
 544241,
 544300,
 544306,
 544493,
 393028,
 393109,
 393108,
 415184,
 415221,
 415223,
 415241,
 493076,
 493091,
 525202,
 525204,
 525638,
 525668,
 613401,
 613434,
 627469,
 627502,
 300158,
 300549,
 300548,
 300862,
 301557,
 302363,
 302362,
 302371,
 302517,
 304075,
 307293,
 307343,
 307342,
 307395,
 307465,
 307519,
 307518,
 307566,
 307575,
 325606,
 361169,
 361239,
 417160,
 417161,
 434962,
 434995,
 448485,
 449357,
 449364,
 458172,
 458229,
 458228,
 458230,
 462761,
 462796,
 462933,
 462935,
 462941,
 463754,
 463842,
 553687,
 553721,
 553720,
 553729,
 567015,
 398469,
 398545,
 398544,
 399199,
 399198,
 399379,
 426882,
 427023,
 435803,
 435819,
 437468,
 437600,
 437616,
 437645,
 437644,
 437658,
 451023,
 451030,
 452815,
 452847,
 452846,
 465644,
 483964,
 495650,
 495743,
 619043,
 619096,
 619290,
 619532,
 619633,
 620203,
 667186,
 667193,
 670639,
 670645,
 670644,
 670850,
 670849,
 671987,
 126112,
 240102,
 240150,
 252465,
 252471,
 395994,
 396017,
 396018,
 396052,
 593119,
 593181,
 593180,
 593655,
 593670,
 594942,
 595966,
 595993,
 595992,
 494465,
 494488,
 494487,
 494504,
 572602,
 572675,
 572674,
 572735,
 573261,
 573577,
 573576,
 573748,
 573754,
 573784,
 581890,
 581945,
 581946,
 581958,
 313266,
 315308,
 464494,
 511098,
 511566,
 526226,
 526789,
 640230,
 640416,
 452299,
 453243,
 564464,
 564586,
 772827,
 772926,
 223683,
 224816,
 299407,
 300790,
 490075,
 491281,
 534829,
 535527,
 445569,
 445842,
 653613,
 256773,
 257528,
 457275,
 457446,
 458723,
 555780,
 556769,
 748251,
 749996,
 302748,
 324983,
 325283,
 228977,
 230882,
 559709,
 559769,
 654680,
 654827,
 474452,
 474856,
 619345,
 619711,
 394012,
 394062,
 392994,
 393848,
 613496,
 613503,
 465956,
 466175,
 466257,
 346447,
 346557,
 787870,
 787871,
 787946,
 788231,
 655107,
 655142,
 715807,
 715838,
 716485,
 716608,
 716632,
 717146,
 178640,
 119372,
 119616,
 369007,
 369383,
 511080,
 511335,
 694681,
 431945,
 591737,
 591910,
 546862,
 547450,
 595075,
 595469,
 351650,
 351771,
 785798,
 786008,
 790457,
 790559,
 409239,
 409636,
 610610,
 611228,
 656350,
 656488,
 352983,
 353097,
 358456,
 358851,
 438127,
 441467,
 441470,
 456800,
 457718,
 658923,
 663153,
 779155,
 779298,
 524877,
 484694,
 484696,
 484954,
 484955,
 600387,
 600551,
 415356,
 415866,
 289718,
 290177,
 572363,
 572491,
 584152,
 586369,
 658618,
 658750,
 308485,
 313001,
 480218,
 480728,
 875335,
 877081,
 932106,
 932415,
 546397,
 547086,
 153822,
 841418,
 841448,
 842133,
 842137,
 953284,
 953527,
 794468,
 794509,
 794541,
 794561,
 794599,
 794702,
 794771,
 794939,
 845536,
 777430,
 777432,
 777612,
 777656,
 777790,
 777813,
 778508,
 884224,
 884226,
 884364,
 884714,
 849117,
 849277,
 968063,
 968193,
 968251,
 968255,
 234655,
 234662,
 842354,
 555108,
 555292,
 911303,
 770468,
 775016,
 775032,
 775035,
 775082,
 775146,
 921177,
 921230,
 921253,
 921306,
 923096,
 923110,
 923112,
 923545,
 923620,
 743212,
 744374,
 745823,
 745851,
 745869,
 745872,
 745941,
 746116,
 803183,
 803245,
 803246,
 803338,
 803614,
 803706,
 965221,
 965809,
 372386,
 372390,
 927538,
 927548,
 937271,
 947977,
 947982,
 959278,
 959288,
 960218,
 960234,
 960261,
 960263,
 961726,
 961728,
 961782,
 961813,
 852992,
 853230,
 980252,
 263868,
 265700,
 341894,
 344062,
 354169,
 354983,
 881015,
 881322,
 60712,
 60721,
 64540,
 64548,
 998867,
 999152,
 660928,
 661113,
 662406,
 662761,
 662798,
 666844,
 666883,
 666947,
 632964,
 635382,
 841746,
 841748,
 865443,
 866448,
 472907,
 472908,
 472933,
 473016,
 473035,
 473151,
 473185,
 473755,
 804205,
 804784,
 968042,
 632776,
 634822,
 634517,
 634744,
 931755,
 932002,
 937930,
 938009,
 938485,
 701188,
 701444,
 806602,
 806722,
 968735,
 968922,
 1009549,
 1009552,
 1009819,
 1016441,
 1021309,
 876075,
 876263,
 846694,
 846727,
 846798,
 846853,
 847386,
 853643,
 675415,
 675646,
 680015,
 680030,
 680075,
 680081,
 680416,
 684687,
 956187,
 956261,
 969813,
 971868,
 574546,
 575723,
 985489,
 985515,
 508856,
 509340,
 728229,
 728563,
 858344,
 937311,
 937880,
 937920,
 559013,
 559089,
 659984,
 919777,
 921126,
 1054504,
 1054506,
 957848,
 957850,
 957954,
 1007438,
 1009186,
 906530,
 906991,
 1006549,
 1007152,
 1056529,
 1056543,
 909415,
 910058,
 912632,
 912633,
 912638,
 912785,
 912829,
 913122,
 997483,
 1024856,
 1024958,
 961434,
 963105,
 929342,
 930433,
 906473,
 907540,
 1007787,
 1007794,
 1007796,
 1007799,
 1007810,
 1007953,
 905311,
 905427,
 793304,
 793872,
 805151,
 805693,
 806201,
 806223,
 508031,
 508032,
 1006454,
 1007927,
 724595,
 724857,
 905888,
 906406,
 944688,
 1025181,
 1025476,
 1000544,
 1001059,
 930795,
 931997,
 965578,
 974699,
 974710,
 990170,
 990173,
 990313,
 990921,
 969484,
 979974,
 1008096,
 1008930,
 1007140,
 1007830,
 870400,
 719737,
 719741,
 1019602,
 1020966,
 946907,
 946941,
 947502,
 947503,
 1031938,
 1031942,
 1032374,
 1032376,
 998449,
 881096,
 881162,
 881335,
 881336,
 881358,
 881359,
 881365,
 881367,
 881665,
 1052994,
 1052995,
 936840,
 936870,
 937530,
 937935,
 937936,
 938014,
 938015,
 1040737,
 1040752,
 1040777,
 1040948,
 1040957,
 1041038,
 1041697,
 1041722,
 1042528,
 1042613,
 1042657,
 1042681,
 1053779,
 877701,
 898511,
 899589,
 5192,
 5287,
 6000,
 6016,
 16060,
 16061,
 6090,
 6096,
 6127,
 6138,
 6143,
 6545,
 2624,
 8813,
 8968,
 10026,
 6678,
 6686,
 1828,
 887854,
 888079,
 894088,
 894092,
 884785,
 891870,
 892335,
 887608,
 887611,
 887634,
 887820,
 888813,
 888816,
 899520,
 899551,
 899749,
 892904,
 893622,
 884940,
 884943,
 885685,
 885686,
 895728,
 896948]

In [16]:
target_index = TimeIntervalColumn_AddedTo_DummyColumns[TimeIntervalColumn_AddedTo_DummyColumns['spn'] == 5246].index.tolist()

TimeIntervalColumn_AddedTo_DummyColumns.loc[target_index, 'time_to_next_SPN5246'] = 0

In [18]:
conditions = [
    TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246'] == 0,
    (TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246'] <= 2) & (TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246'] > 0),
    (TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246'] > 2) & (TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246'] <= 24),
    (TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246'] > 24) & (TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246'] < 239999976),
    TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246'] == timedelta(days=9999999)
]

choices = [3, 2, 1, 0, 9999999]
TimeIntervalColumn_AddedTo_DummyColumns['time_interval_to_SPN5246_class'] = np.select(conditions, choices)

In [19]:
TimeIntervalColumn_AddedTo_DummyColumns[TimeIntervalColumn_AddedTo_DummyColumns['spn'] == 5246]['spn_fmi'].value_counts()

spn_fmi
5246.0_0.0     622
5246.0_16.0    144
5246.0_15.0    103
5246.0_19.0     61
5246.0_14.0      8
Name: count, dtype: int64

In [20]:
TimeIntervalColumn_AddedTo_DummyColumns[TimeIntervalColumn_AddedTo_DummyColumns['time_interval_to_SPN5246_class'] == 3]['spn_fmi'].value_counts()

spn_fmi
5246.0_0.0     622
5246.0_16.0    144
5246.0_15.0    103
5246.0_19.0     61
5246.0_14.0      8
Name: count, dtype: int64

In [21]:
Pre2019_df = TimeIntervalColumn_AddedTo_DummyColumns[TimeIntervalColumn_AddedTo_DummyColumns['EventTimeStamp'] < datetime(2019, 1, 1)]
Pre2019_df

,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,...,Speed,SwitchedBatteryVoltage,Throttle,TurboBoostPressure,spn_fmi,is_fullderate,is_fullderate_group,EquipID_Index,time_to_next_SPN5246,time_interval_to_SPN5246_class
43931,48303,49415,2363162,2015-05-11 13:11:20,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,4.475814,3276.75,14.4,0.58,639.0_2.0,0,0,301_0,1.027800e+04,0
45693,50251,51363,2400445,2015-05-13 08:22:32,Condition Exists Cruise Control Enable Switch,NaN,unknown,unknown,unknown,unknown,...,64.637170,3276.75,89.6,4.64,596.0_31.0,0,0,301_0,1.023481e+04,0
50271,55260,57330,2482983,2015-05-18 09:34:05,Abnormal Rate of Change Aftertreatment 1 Outle...,NaN,PC4__1284P4C_2*,6U13D13,MX,PCAR,...,63.525490,3276.75,0.0,20.30,3226.0_10.0,0,0,301_0,1.011362e+04,0
54326,59636,61706,2554027,2015-05-21 13:57:35,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,4.364162,3276.75,12.0,1.45,639.0_2.0,0,0,301_0,1.003723e+04,0
54418,59731,61801,2555325,2015-05-21 14:54:32,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,NaN,NaN,639.0_2.0,0,0,301_0,1.003628e+04,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4036,4494,4495,1052146,2015-02-24 16:24:05,Low (Severity Medium) Catalyst Tank Level,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,NaN,NaN,NaN,NaN,1761.0_18.0,0,0,R1762_0,2.400000e+08,0
5907,6438,6439,1089561,2015-02-26 13:12:11,NaN,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,2.058292,3276.75,0.0,0.29,5848.0_9.0,0,0,R1762_0,2.400000e+08,0
5915,6446,6447,1090499,2015-02-26 13:50:59,NaN,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,NaN,NaN,NaN,NaN,5848.0_9.0,0,0,R1762_0,2.400000e+08,0
4472,4952,4953,1059704,2015-02-25 06:08:43,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,4.378725,3276.75,0.0,1.74,639.0_2.0,0,0,R1764_0,2.400000e+08,0
4512,4999,5000,1060204,2015-02-25 06:38:40,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,NaN,NaN,639.0_2.0,0,0,R1764_0,2.400000e+08,0

In [22]:
Pre2019_df_AltApproach = TimeIntervalColumn_AddedTo_DummyColumns[TimeIntervalColumn_AddedTo_DummyColumns['EventTimeStamp'] < pd.Timestamp('2019-01-01')]
Pre2019_df_AltApproach

,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,...,Speed,SwitchedBatteryVoltage,Throttle,TurboBoostPressure,spn_fmi,is_fullderate,is_fullderate_group,EquipID_Index,time_to_next_SPN5246,time_interval_to_SPN5246_class
43931,48303,49415,2363162,2015-05-11 13:11:20,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,4.475814,3276.75,14.4,0.58,639.0_2.0,0,0,301_0,1.027800e+04,0
45693,50251,51363,2400445,2015-05-13 08:22:32,Condition Exists Cruise Control Enable Switch,NaN,unknown,unknown,unknown,unknown,...,64.637170,3276.75,89.6,4.64,596.0_31.0,0,0,301_0,1.023481e+04,0
50271,55260,57330,2482983,2015-05-18 09:34:05,Abnormal Rate of Change Aftertreatment 1 Outle...,NaN,PC4__1284P4C_2*,6U13D13,MX,PCAR,...,63.525490,3276.75,0.0,20.30,3226.0_10.0,0,0,301_0,1.011362e+04,0
54326,59636,61706,2554027,2015-05-21 13:57:35,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,4.364162,3276.75,12.0,1.45,639.0_2.0,0,0,301_0,1.003723e+04,0
54418,59731,61801,2555325,2015-05-21 14:54:32,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,NaN,NaN,639.0_2.0,0,0,301_0,1.003628e+04,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4036,4494,4495,1052146,2015-02-24 16:24:05,Low (Severity Medium) Catalyst Tank Level,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,NaN,NaN,NaN,NaN,1761.0_18.0,0,0,R1762_0,2.400000e+08,0
5907,6438,6439,1089561,2015-02-26 13:12:11,NaN,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,2.058292,3276.75,0.0,0.29,5848.0_9.0,0,0,R1762_0,2.400000e+08,0
5915,6446,6447,1090499,2015-02-26 13:50:59,NaN,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,NaN,NaN,NaN,NaN,5848.0_9.0,0,0,R1762_0,2.400000e+08,0
4472,4952,4953,1059704,2015-02-25 06:08:43,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,4.378725,3276.75,0.0,1.74,639.0_2.0,0,0,R1764_0,2.400000e+08,0
4512,4999,5000,1060204,2015-02-25 06:38:40,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,NaN,NaN,639.0_2.0,0,0,R1764_0,2.400000e+08,0

In [23]:
Pre2019_df.to_csv('../data/Pre2019_df_Cat9999999.csv')

In [24]:
In2019_df = TimeIntervalColumn_AddedTo_DummyColumns[TimeIntervalColumn_AddedTo_DummyColumns['EventTimeStamp'] > datetime(2018, 12, 31)]
In2019_df

,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,...,Speed,SwitchedBatteryVoltage,Throttle,TurboBoostPressure,spn_fmi,is_fullderate,is_fullderate_group,EquipID_Index,time_to_next_SPN5246,time_interval_to_SPN5246_class
952775,1062090,1104925,73930906,2019-01-11 12:51:18,High Voltage (Fuel Level),NaN,unknown,unknown,unknown,unknown,...,46.52031,NaN,34.4,13.05,96.0_3.0,0,1,301_1,239999976.0,0
952776,1062091,1104926,73930907,2019-01-11 12:51:18,High Voltage (Left Fuel Level Sensor),NaN,unknown,unknown,unknown,unknown,...,46.52031,NaN,34.4,13.05,829.0_3.0,0,1,301_1,239999976.0,0
952781,1062096,1104931,73934247,2019-01-11 13:11:40,High Voltage (Fuel Level),NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,NaN,NaN,96.0_3.0,0,1,301_1,239999976.0,0
952782,1062097,1104932,73934248,2019-01-11 13:11:40,High Voltage (Left Fuel Level Sensor),NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,NaN,NaN,829.0_3.0,0,1,301_1,239999976.0,0
952809,1062135,1104970,73942005,2019-01-11 13:13:38,High Voltage (Fuel Level),NaN,unknown,unknown,unknown,unknown,...,0.00000,NaN,0.0,1.16,96.0_3.0,0,1,301_1,239999976.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
977126,1089938,1137548,80503703,2019-03-16 11:22:32,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,AAAI000051*AAAM010056*Z091290 *A82J170202A_b...,6232171647,EC80ESP,BNDWS,...,NaN,NaN,NaN,NaN,639.0_2.0,0,0,105437340_0,239999976.0,0
977150,1089962,1137572,80509396,2019-03-16 11:24:04,Special Instructions Engine Starter Solenoid L...,NaN,5569997 *E250.e003*,K1243673,FAOM-xx810S-EC3,EATON,...,0.00000,NaN,100.0,0.29,1321.0_14.0,0,0,105437340_0,239999976.0,0
977151,1089963,1137573,80509397,2019-03-16 11:27:41,NaN,NaN,5569997 *E250.e003*,K1243673,FAOM-xx810S-EC3,EATON,...,0.00000,NaN,100.0,0.29,520321.0_13.0,0,0,105437340_0,239999976.0,0
978491,1091502,1139112,80907838,2019-03-20 10:57:34,Special Instructions Engine Starter Solenoid L...,NaN,NaN,K1243673,FAOM-xx810S-EC3,EATON,...,NaN,NaN,NaN,NaN,1321.0_14.0,0,0,105437340_0,239999976.0,0
978891,1091973,1139583,81025027,2019-03-21 10:05:14,NaN,NaN,5569997 *E250.e003*,K1243673,FAOM-xx810S-EC3,EATON,...,NaN,NaN,NaN,NaN,520321.0_13.0,0,0,105437340_0,239999976.0,0

In [25]:
In2019_df_AltApproach = TimeIntervalColumn_AddedTo_DummyColumns[TimeIntervalColumn_AddedTo_DummyColumns['EventTimeStamp'] > pd.Timestamp('2018-12-31')]
In2019_df_AltApproach

,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,...,Speed,SwitchedBatteryVoltage,Throttle,TurboBoostPressure,spn_fmi,is_fullderate,is_fullderate_group,EquipID_Index,time_to_next_SPN5246,time_interval_to_SPN5246_class
952775,1062090,1104925,73930906,2019-01-11 12:51:18,High Voltage (Fuel Level),NaN,unknown,unknown,unknown,unknown,...,46.52031,NaN,34.4,13.05,96.0_3.0,0,1,301_1,239999976.0,0
952776,1062091,1104926,73930907,2019-01-11 12:51:18,High Voltage (Left Fuel Level Sensor),NaN,unknown,unknown,unknown,unknown,...,46.52031,NaN,34.4,13.05,829.0_3.0,0,1,301_1,239999976.0,0
952781,1062096,1104931,73934247,2019-01-11 13:11:40,High Voltage (Fuel Level),NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,NaN,NaN,96.0_3.0,0,1,301_1,239999976.0,0
952782,1062097,1104932,73934248,2019-01-11 13:11:40,High Voltage (Left Fuel Level Sensor),NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,NaN,NaN,829.0_3.0,0,1,301_1,239999976.0,0
952809,1062135,1104970,73942005,2019-01-11 13:13:38,High Voltage (Fuel Level),NaN,unknown,unknown,unknown,unknown,...,0.00000,NaN,0.0,1.16,96.0_3.0,0,1,301_1,239999976.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
977126,1089938,1137548,80503703,2019-03-16 11:22:32,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,AAAI000051*AAAM010056*Z091290 *A82J170202A_b...,6232171647,EC80ESP,BNDWS,...,NaN,NaN,NaN,NaN,639.0_2.0,0,0,105437340_0,239999976.0,0
977150,1089962,1137572,80509396,2019-03-16 11:24:04,Special Instructions Engine Starter Solenoid L...,NaN,5569997 *E250.e003*,K1243673,FAOM-xx810S-EC3,EATON,...,0.00000,NaN,100.0,0.29,1321.0_14.0,0,0,105437340_0,239999976.0,0
977151,1089963,1137573,80509397,2019-03-16 11:27:41,NaN,NaN,5569997 *E250.e003*,K1243673,FAOM-xx810S-EC3,EATON,...,0.00000,NaN,100.0,0.29,520321.0_13.0,0,0,105437340_0,239999976.0,0
978491,1091502,1139112,80907838,2019-03-20 10:57:34,Special Instructions Engine Starter Solenoid L...,NaN,NaN,K1243673,FAOM-xx810S-EC3,EATON,...,NaN,NaN,NaN,NaN,1321.0_14.0,0,0,105437340_0,239999976.0,0
978891,1091973,1139583,81025027,2019-03-21 10:05:14,NaN,NaN,5569997 *E250.e003*,K1243673,FAOM-xx810S-EC3,EATON,...,NaN,NaN,NaN,NaN,520321.0_13.0,0,0,105437340_0,239999976.0,0

In [26]:
In2019_df.to_csv('../data/In2019_df_Cat9999999.csv')

In [27]:
TimeIntervalColumn_AddedTo_DummyColumns.to_csv('../data/MergedFullDataSet_TimeIntervalLabeled_PerTruck_Cat9999999.csv')