In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import r2_score, mean_squared_error, root_mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from datetime import datetime, timedelta

In [2]:
explore = pd.read_csv('../data/Merged_FullDataSet_withDummyColumns_y_TimeIntervalClass_StillNeedToCalcByTruck.csv')
explore

/var/folders/nl/hqcw9pqd0ns4q0b61syv0q2m0000gn/T/ipykernel_74275/459539421.py:1: DtypeWarning: Columns (17,44,1043) have mixed types. Specify dtype option on import or set low_memory=False.
  explore = pd.read_csv('../data/Merged_FullDataSet_withDummyColumns_y_TimeIntervalClass_StillNeedToCalcByTruck.csv')

,Unnamed: 0.1,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,...,spn_fmi_97.0_3.0,spn_fmi_97.0_4.0,spn_fmi_976.0_9.0,spn_fmi_98.0_18.0,spn_fmi_98.0_5.0,is_fullderate,is_fullderate_group,EquipID_Index,time_to_next_SPN5246,time_interval_to_SPN5246_class
0,0,0,1,990349,2015-02-21 10:47:13,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1439_0,1 days 18:18:31,0
1,1,1,2,990360,2015-02-21 11:34:34,NaN,NaN,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1439_0,1 days 17:31:10,0
2,2,2,3,990364,2015-02-21 11:35:31,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1369_0,1 days 17:30:13,0
3,3,3,4,990370,2015-02-21 11:35:33,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1369_0,1 days 17:30:11,0
4,4,4,5,990416,2015-02-21 11:39:41,NaN,NaN,22281684P01*22357957P01*22362082P01*,13063430,0USA13_13_0415_2238A,...,False,False,False,False,False,0,0,1674_0,1 days 17:26:03,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057044,1057044,1187330,1248454,123904424,2020-03-06 14:00:26,Low (Severity Low) Catalyst Tank Level,NaN,04384413*22383729*082218154102*60701732*G1*BGT*,80156139,6X1u17D1500000000,...,False,False,False,False,False,0,0,2282_0,NaN,0
1057045,1057045,1187331,1248455,123905139,2020-03-06 14:04:23,Condition Exists Engine Protection Torque Derate,NaN,04358814*06099720*030816202706*09400153*G1*BDR*,79932020,6X1u13D1500000000,...,False,False,False,False,False,0,0,1994_0,NaN,0
1057046,1057046,1187332,1248456,123905996,2020-03-06 14:13:38,Abnormal Rate of Change Aftertreatment 1 Intak...,NaN,05317106*05100987*050719120655*09401585*G1*BDR*,79880653,6X1u13D1500000000,...,False,False,False,False,False,0,0,1850_0,NaN,0
1057047,1057047,1187333,1248457,123906113,2020-03-06 14:14:13,Low (Severity Medium) Engine Coolant Level,NaN,04384413*22544852*090619141107*60701756*G1*BGT*,NaN,NaN,...,False,False,False,False,False,0,0,2377_0,NaN,0
1057048,1057048,1187334,1248458,123906131,2020-03-06 14:15:34,Low (Severity Medium) Engine Coolant Level,NaN,04384413*22544852*090619141107*60701756*G1*BGT*,NaN,NaN,...,False,False,False,False,False,0,0,2377_0,NaN,0

In [3]:
explore.head(9000)

,Unnamed: 0.1,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,...,spn_fmi_97.0_3.0,spn_fmi_97.0_4.0,spn_fmi_976.0_9.0,spn_fmi_98.0_18.0,spn_fmi_98.0_5.0,is_fullderate,is_fullderate_group,EquipID_Index,time_to_next_SPN5246,time_interval_to_SPN5246_class
0,0,0,1,990349,2015-02-21 10:47:13,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1439_0,1 days 18:18:31,0
1,1,1,2,990360,2015-02-21 11:34:34,NaN,NaN,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1439_0,1 days 17:31:10,0
2,2,2,3,990364,2015-02-21 11:35:31,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1369_0,1 days 17:30:13,0
3,3,3,4,990370,2015-02-21 11:35:33,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1369_0,1 days 17:30:11,0
4,4,4,5,990416,2015-02-21 11:39:41,NaN,NaN,22281684P01*22357957P01*22362082P01*,13063430,0USA13_13_0415_2238A,...,False,False,False,False,False,0,0,1674_0,1 days 17:26:03,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,8995,9896,9897,1436145,2015-03-19 09:20:59,Abnormal Update Rate Tire Location,NaN,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1620_0,2 days 07:04:00,0
8996,8996,9897,9898,1436203,2015-03-19 09:23:36,Condition Exists Engine Protection Torque Derate,NaN,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1328_0,2 days 07:01:23,0
8997,8997,9898,9899,1436211,2015-03-19 09:24:19,Low (Severity Low) Engine Coolant Level,NaN,04993120*00179527*060712145341*07700027*I0*BBZ*,79619114,6X1u10D1500000000,...,False,False,False,False,False,0,0,1584_0,2 days 07:00:40,0
8998,8998,9899,9900,1436246,2015-03-19 09:26:34,Low (Severity Low) Engine Coolant Level,NaN,04993120*00179527*060712145341*07700027*I0*BBZ*,79619114,6X1u10D1500000000,...,False,False,False,False,False,0,0,1584_0,2 days 06:58:25,0
8999,8999,9900,9901,1436257,2015-03-19 09:26:52,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1579_0,2 days 06:58:07,0

In [4]:
light_on_Merged_FullDataSet = pd.read_csv('../data/MergedData.csv')
light_on = light_on_Merged_FullDataSet.head(9000)

/var/folders/nl/hqcw9pqd0ns4q0b61syv0q2m0000gn/T/ipykernel_74275/117179744.py:1: DtypeWarning: Columns (16,22,23,26,27,29,30,31,32,33,34,35,36,38,42,43,44,45) have mixed types. Specify dtype option on import or set low_memory=False.
  light_on_Merged_FullDataSet = pd.read_csv('../data/MergedData.csv')

convert columns to appropriate format

In [5]:
cols = ['spn', 'fmi', 'AcceleratorPedal', 'BarometricPressure', 'CruiseControlSetSpeed', 'DistanceLtd', 'EngineCoolantTemperature', 'EngineLoad', 'EngineOilPressure', 'EngineOilTemperature', 'EngineRpm', 'EngineTimeLtd', 'FuelLevel', 'FuelLtd', 'FuelRate', 'FuelTemperature', 'IntakeManifoldTemperature', 'LampStatus', 'Speed', 'Throttle', 'TurboBoostPressure']
light_on[cols] = light_on[cols].apply(pd.to_numeric, errors='coerce', axis=1)
light_on

/var/folders/nl/hqcw9pqd0ns4q0b61syv0q2m0000gn/T/ipykernel_74275/3486558198.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  light_on[cols] = light_on[cols].apply(pd.to_numeric, errors='coerce', axis=1)

,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,...,FuelTemperature,IgnStatus,IntakeManifoldTemperature,LampStatus,ParkingBrake,ServiceDistance,Speed,SwitchedBatteryVoltage,Throttle,TurboBoostPressure
0,0,1,990349,2015-02-21 10:47:13.000,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,NaN,False,78.8,1023.0,True,NaN,0.00000,3276.75,NaN,0.00
1,1,2,990360,2015-02-21 11:34:34.000,NaN,NaN,unknown,unknown,unknown,unknown,...,NaN,True,NaN,1279.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,3,990364,2015-02-21 11:35:31.000,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,NaN,1279.0,NaN,NaN,NaN,NaN,NaN,NaN
3,3,4,990370,2015-02-21 11:35:33.000,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,unknown,...,NaN,True,NaN,1279.0,NaN,NaN,NaN,NaN,NaN,NaN
4,4,5,990416,2015-02-21 11:39:41.000,NaN,NaN,22281684P01*22357957P01*22362082P01*,13063430,0USA13_13_0415_2238A,VOLVO,...,NaN,NaN,NaN,16639.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,9896,9897,1436145,2015-03-19 09:20:59.000,Abnormal Update Rate Tire Location,NaN,unknown,unknown,unknown,unknown,...,32.0,True,116.6,1279.0,False,NaN,0.00000,3276.75,0.0,0.29
8996,9897,9898,1436203,2015-03-19 09:23:36.000,Condition Exists Engine Protection Torque Derate,NaN,unknown,unknown,unknown,unknown,...,NaN,True,66.2,18431.0,False,NaN,66.82653,3276.75,NaN,8.70
8997,9898,9899,1436211,2015-03-19 09:24:19.000,Low (Severity Low) Engine Coolant Level,NaN,04993120*00179527*060712145341*07700027*I0*BBZ*,79619114,6X1u10D1500000000,CMMNS,...,NaN,True,95.0,1023.0,NaN,NaN,31.42779,3276.75,NaN,8.41
8998,9899,9900,1436246,2015-03-19 09:26:34.000,Low (Severity Low) Engine Coolant Level,NaN,04993120*00179527*060712145341*07700027*I0*BBZ*,79619114,6X1u10D1500000000,CMMNS,...,NaN,NaN,NaN,1023.0,NaN,NaN,NaN,NaN,NaN,NaN
8999,9900,9901,1436257,2015-03-19 09:26:52.000,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,NaN,1023.0,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
light_on['spn_fmi'] = light_on['spn'].astype(str) + '_' + light_on['fmi'].astype(str)
light_on

/var/folders/nl/hqcw9pqd0ns4q0b61syv0q2m0000gn/T/ipykernel_74275/2423738569.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  light_on['spn_fmi'] = light_on['spn'].astype(str) + '_' + light_on['fmi'].astype(str)

,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,...,IgnStatus,IntakeManifoldTemperature,LampStatus,ParkingBrake,ServiceDistance,Speed,SwitchedBatteryVoltage,Throttle,TurboBoostPressure,spn_fmi
0,0,1,990349,2015-02-21 10:47:13.000,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,78.8,1023.0,True,NaN,0.00000,3276.75,NaN,0.00,111.0_17.0
1,1,2,990360,2015-02-21 11:34:34.000,NaN,NaN,unknown,unknown,unknown,unknown,...,True,NaN,1279.0,NaN,NaN,NaN,NaN,NaN,NaN,629.0_12.0
2,2,3,990364,2015-02-21 11:35:31.000,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,1279.0,NaN,NaN,NaN,NaN,NaN,NaN,1807.0_2.0
3,3,4,990370,2015-02-21 11:35:33.000,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,unknown,...,True,NaN,1279.0,NaN,NaN,NaN,NaN,NaN,NaN,1807.0_2.0
4,4,5,990416,2015-02-21 11:39:41.000,NaN,NaN,22281684P01*22357957P01*22362082P01*,13063430,0USA13_13_0415_2238A,VOLVO,...,NaN,NaN,16639.0,NaN,NaN,NaN,NaN,NaN,NaN,4364.0_17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,9896,9897,1436145,2015-03-19 09:20:59.000,Abnormal Update Rate Tire Location,NaN,unknown,unknown,unknown,unknown,...,True,116.6,1279.0,False,NaN,0.00000,3276.75,0.0,0.29,929.0_9.0
8996,9897,9898,1436203,2015-03-19 09:23:36.000,Condition Exists Engine Protection Torque Derate,NaN,unknown,unknown,unknown,unknown,...,True,66.2,18431.0,False,NaN,66.82653,3276.75,NaN,8.70,1569.0_31.0
8997,9898,9899,1436211,2015-03-19 09:24:19.000,Low (Severity Low) Engine Coolant Level,NaN,04993120*00179527*060712145341*07700027*I0*BBZ*,79619114,6X1u10D1500000000,CMMNS,...,True,95.0,1023.0,NaN,NaN,31.42779,3276.75,NaN,8.41,111.0_17.0
8998,9899,9900,1436246,2015-03-19 09:26:34.000,Low (Severity Low) Engine Coolant Level,NaN,04993120*00179527*060712145341*07700027*I0*BBZ*,79619114,6X1u10D1500000000,CMMNS,...,NaN,NaN,1023.0,NaN,NaN,NaN,NaN,NaN,NaN,111.0_17.0
8999,9900,9901,1436257,2015-03-19 09:26:52.000,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,NaN,NaN,1023.0,NaN,NaN,NaN,NaN,NaN,NaN,111.0_17.0

In [7]:
dummy_columns = pd.get_dummies(light_on, columns = ['spn_fmi'])

In [8]:
#dummy_columns.loc[:, dummy_columns.columns.str.startswith('spn')] = dummy_columns.loc[:, dummy_columns.columns.str.startswith('spn')].astype('int')

In [9]:
#dummy_columns.to_csv('../data/TwentyRows_Preceding_SPN5246_LightOn_Dummy_Columns.csv')

In [10]:
dummy_columns

,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,...,spn_fmi_862.0_3.0,spn_fmi_905.0_19.0,spn_fmi_907.0_19.0,spn_fmi_91.0_2.0,spn_fmi_917.0_9.0,spn_fmi_929.0_9.0,spn_fmi_96.0_3.0,spn_fmi_96.0_4.0,spn_fmi_97.0_15.0,spn_fmi_97.0_16.0
0,0,1,990349,2015-02-21 10:47:13.000,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,False,False,False,False
1,1,2,990360,2015-02-21 11:34:34.000,NaN,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,False,False,False,False
2,2,3,990364,2015-02-21 11:35:31.000,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,False,False,False,False
3,3,4,990370,2015-02-21 11:35:33.000,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,False,False,False,False
4,4,5,990416,2015-02-21 11:39:41.000,NaN,NaN,22281684P01*22357957P01*22362082P01*,13063430,0USA13_13_0415_2238A,VOLVO,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,9896,9897,1436145,2015-03-19 09:20:59.000,Abnormal Update Rate Tire Location,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,True,False,False,False,False
8996,9897,9898,1436203,2015-03-19 09:23:36.000,Condition Exists Engine Protection Torque Derate,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,False,False,False,False
8997,9898,9899,1436211,2015-03-19 09:24:19.000,Low (Severity Low) Engine Coolant Level,NaN,04993120*00179527*060712145341*07700027*I0*BBZ*,79619114,6X1u10D1500000000,CMMNS,...,False,False,False,False,False,False,False,False,False,False
8998,9899,9900,1436246,2015-03-19 09:26:34.000,Low (Severity Low) Engine Coolant Level,NaN,04993120*00179527*060712145341*07700027*I0*BBZ*,79619114,6X1u10D1500000000,CMMNS,...,False,False,False,False,False,False,False,False,False,False
8999,9900,9901,1436257,2015-03-19 09:26:52.000,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,False,False,False,False

In [11]:
dummy_columns['is_fullderate'] = (dummy_columns['spn'] == 5246).astype(int)

In [12]:
dummy_columns = dummy_columns.sort_values(['EquipmentID', 'EventTimeStamp'])
dummy_columns['is_fullderate_group'] = dummy_columns.groupby('EquipmentID')['is_fullderate'].cumsum()

In [13]:
Num_of_FullDerates_inDataSet = dummy_columns['is_fullderate_group'].sum()
Num_of_FullDerates_inDataSet # 1

np.int64(580)

In [14]:
dummy_columns['EquipID_Index'] = dummy_columns['EquipmentID'].astype(str) + '_' + dummy_columns['is_fullderate_group'].astype(str)

dummy_columns.to_csv('../data/TwentyRows_Preceding_SPN5246_LightOn_Truck_Identifier_SubsequentTrialRun.csv')

In [26]:
def check_time_intervals(df, EventTimeStamp='EventTimeStamp', condition_column='spn', condition_value=5246, interval_column_name='time_to_next_SPN5246'):
    """
    Calculate the time interval between the current row and the next row(s) that meet a specific condition.
    
    Parameters:
    -----------
    df : pandas.DataFrame
        The dataframe containing the timestamp and condition columns.
    EventTimeStamp : str
        The name of the column containing datetime values.
    condition_column : str, optional
        The name of the column to check for the condition. If None, all rows are considered.
    condition_value : any, optional
        The value to check for in the condition column. If None, all rows are considered.
    interval_column_name : str, optional
        The name for the new column that will store the time interval information.
        Default is 'time_to_next_condition'.
    
    Returns:
    --------
    pandas.DataFrame
        The original dataframe with an additional column showing the time interval
        to the next row meeting the condition.
    """
    # Ensure the timestamp column is in datetime format
    df[EventTimeStamp] = pd.to_datetime(df[EventTimeStamp])
    
    # Create a copy of the dataframe to avoid modifying the original
    result_df = df.copy()
    
    # Add a column to store the time intervals with the specified name
    result_df[interval_column_name] = timedelta(days=9999999)  # Initialize with a large timedelta

    
    # Filter rows that meet the condition if a condition is specified
    if condition_column is not None and condition_value is not None:
        condition_rows = df[df[condition_column] == condition_value]
    else:
        condition_rows = df
    
    # For each row in the dataframe
    for i in range(len(df) - 1):
        current_time = df.iloc[i][EventTimeStamp]
        current_EquipmentID = df.iloc[i]['EquipmentID']
        
        # Find the next row that meets the condition and is after the current row
        next_condition_rows = condition_rows[(condition_rows[EventTimeStamp] > current_time) & (condition_rows['EquipmentID'] == current_EquipmentID)]
        
        if not next_condition_rows.empty:
            # Get the earliest next condition time
            next_condition_time = next_condition_rows[EventTimeStamp].min()
            
            # Calculate the time difference
            time_diff = next_condition_time - current_time
            
            # Store the result in the specified column
            result_df.iloc[i, result_df.columns.get_loc(interval_column_name)] = time_diff
    
    return result_df

In [27]:
TimeIntervalColumn_AddedTo_DummyColumns = check_time_intervals(dummy_columns, EventTimeStamp='EventTimeStamp', condition_column='spn', condition_value=5246, interval_column_name='time_to_next_SPN5246') 
TimeIntervalColumn_AddedTo_DummyColumns

,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,...,spn_fmi_917.0_9.0,spn_fmi_929.0_9.0,spn_fmi_96.0_3.0,spn_fmi_96.0_4.0,spn_fmi_97.0_15.0,spn_fmi_97.0_16.0,is_fullderate,is_fullderate_group,EquipID_Index,time_to_next_SPN5246
2150,2479,2480,1017664,2015-02-23 10:24:18,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,0,0,1328_0,9999999 days
2152,2482,2483,1017697,2015-02-23 10:26:58,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,0,0,1328_0,9999999 days
4537,5080,5081,1061221,2015-02-25 07:24:50,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,0,0,1328_0,9999999 days
4560,5103,5104,1061428,2015-02-25 07:34:24,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,0,0,1328_0,9999999 days
5941,6526,6527,1097093,2015-02-26 20:14:29,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,0,0,1328_0,9999999 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3991,4494,4495,1052146,2015-02-24 16:24:05,Low (Severity Medium) Catalyst Tank Level,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,False,False,False,False,False,False,0,0,R1762_0,9999999 days
5856,6438,6439,1089561,2015-02-26 13:12:11,NaN,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,False,False,False,False,False,False,0,0,R1762_0,9999999 days
5864,6446,6447,1090499,2015-02-26 13:50:59,NaN,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,False,False,False,False,False,False,0,0,R1762_0,9999999 days
4423,4952,4953,1059704,2015-02-25 06:08:43,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,0,0,R1764_0,9999999 days
4463,4999,5000,1060204,2015-02-25 06:38:40,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,0,0,R1764_0,9999999 days

In [28]:
def convert_to_hours(delta):
    total_seconds = delta.dt.total_seconds()
    hours = (total_seconds / 3600).astype(float)
    return hours

In [29]:
TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246'] = convert_to_hours(TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246']) 
TimeIntervalColumn_AddedTo_DummyColumns

,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,...,spn_fmi_917.0_9.0,spn_fmi_929.0_9.0,spn_fmi_96.0_3.0,spn_fmi_96.0_4.0,spn_fmi_97.0_15.0,spn_fmi_97.0_16.0,is_fullderate,is_fullderate_group,EquipID_Index,time_to_next_SPN5246
2150,2479,2480,1017664,2015-02-23 10:24:18,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,0,0,1328_0,239999976.0
2152,2482,2483,1017697,2015-02-23 10:26:58,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,0,0,1328_0,239999976.0
4537,5080,5081,1061221,2015-02-25 07:24:50,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,0,0,1328_0,239999976.0
4560,5103,5104,1061428,2015-02-25 07:34:24,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,0,0,1328_0,239999976.0
5941,6526,6527,1097093,2015-02-26 20:14:29,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,0,0,1328_0,239999976.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3991,4494,4495,1052146,2015-02-24 16:24:05,Low (Severity Medium) Catalyst Tank Level,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,False,False,False,False,False,False,0,0,R1762_0,239999976.0
5856,6438,6439,1089561,2015-02-26 13:12:11,NaN,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,False,False,False,False,False,False,0,0,R1762_0,239999976.0
5864,6446,6447,1090499,2015-02-26 13:50:59,NaN,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,False,False,False,False,False,False,0,0,R1762_0,239999976.0
4423,4952,4953,1059704,2015-02-25 06:08:43,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,0,0,R1764_0,239999976.0
4463,4999,5000,1060204,2015-02-25 06:38:40,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,False,0,0,R1764_0,239999976.0

In [30]:
conditions = [
    TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246'] < 2,
    (TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246'] >= 2) & (TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246'] <= 6),
    TimeIntervalColumn_AddedTo_DummyColumns['time_to_next_SPN5246'] > 6
]

choices = [2, 1, 0]
TimeIntervalColumn_AddedTo_DummyColumns['time_interval_to_SPN5246_class'] = np.select(conditions, choices)

In [ ]:
TimeIntervalColumn_AddedTo_DummyColumns['spn'] = TimeIntervalColumn_AddedTo_DummyColumns['spn'].astype(str)
TimeIntervalColumn_AddedTo_DummyColumns['fmi'] = TimeIntervalColumn_AddedTo_DummyColumns['fmi'].astype(str)

,Unnamed: 0,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,...,spn_fmi_929.0_9.0,spn_fmi_96.0_3.0,spn_fmi_96.0_4.0,spn_fmi_97.0_15.0,spn_fmi_97.0_16.0,is_fullderate,is_fullderate_group,EquipID_Index,time_to_next_SPN5246,time_interval_to_SPN5246_class
2150,2479,2480,1017664,2015-02-23 10:24:18,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1328_0,239999976.0,0
2152,2482,2483,1017697,2015-02-23 10:26:58,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1328_0,239999976.0,0
4537,5080,5081,1061221,2015-02-25 07:24:50,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1328_0,239999976.0,0
4560,5103,5104,1061428,2015-02-25 07:34:24,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1328_0,239999976.0,0
5941,6526,6527,1097093,2015-02-26 20:14:29,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,0,0,1328_0,239999976.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3991,4494,4495,1052146,2015-02-24 16:24:05,Low (Severity Medium) Catalyst Tank Level,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,False,False,False,False,False,0,0,R1762_0,239999976.0,0
5856,6438,6439,1089561,2015-02-26 13:12:11,NaN,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,False,False,False,False,False,0,0,R1762_0,239999976.0,0
5864,6446,6447,1090499,2015-02-26 13:50:59,NaN,NaN,05317106*04119044*051914190353*09400015*G1*BDR*,79751302,6X1u13D1500000000,CMMNS,...,False,False,False,False,False,0,0,R1762_0,239999976.0,0
4423,4952,4953,1059704,2015-02-25 06:08:43,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,0,0,R1764_0,239999976.0,0
4463,4999,5000,1060204,2015-02-25 06:38:40,Incorrect Data J1939 Network #1 Primary Vehicl...,NaN,unknown,unknown,unknown,unknown,...,False,False,False,False,False,0,0,R1764_0,239999976.0,0

In [32]:
TimeIntervalColumn_AddedTo_DummyColumns.to_csv('../data/ZachApproach_TimeIntervalClassification_PerTruck.csv')